# Generated by Django 6.0.2 on 2026-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_branch_user_assigned_tests_user_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Bo‘lim'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='branch',
        ),
    ]
