# Generated by Django 6.0.2 on 2026-02-11 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fix_nullable_phone_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d[\\d\\s\\-()]{7,}$', 'Telefon raqam noto‘g‘ri formatda.')], verbose_name='Telefon'),
        ),
    ]
