# Generated by Django 6.0.2 on 2026-02-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_test_created_at'),
        ('users', '0006_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AddField(
            model_name='department',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, related_name='departments', to='exams.test', verbose_name='Testlar (bo‘lim bo‘yicha)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
