# Generated by Django 6.0.2 on 2026-02-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_test_created_at'),
        ('users', '0007_alter_department_options_department_assigned_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, related_name='departments', to='exams.test', verbose_name='Majburiy testlar'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
