# Generated by Django 6.0.2 on 2026-02-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='assigned_tests',
        ),
    ]
