# Generated by Django 6.0.2 on 2026-02-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
    ]
