# Generated by Django 6.0.2 on 2026-02-11 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='code',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='test',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (min)'),
        ),
        migrations.AddField(
            model_name='test',
            name='pass_percent',
            field=models.PositiveIntegerField(default=60, verbose_name='O‘tish foizi (%)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='To‘g‘ri javob'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', related_query_name='exam_attempt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attemptlar',
            },
        ),
        migrations.CreateModel(
            name='AssignedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('attempts_limit', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='exams.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assigned_tests', related_query_name='exam_assigned_test', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test biriktirish',
                'verbose_name_plural': 'Test biriktirishlar',
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('earned_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='exams.question')),
            ],
            options={
                'verbose_name': 'Attempt javobi',
                'verbose_name_plural': 'Attempt javoblari',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
