# Generated by Django 6.0.2 on 2026-02-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_test_code_test_duration_minutes_test_pass_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Attempt', 'verbose_name_plural': 'Urinishlar'},
        ),
        migrations.AlterModelOptions(
            name='attemptanswer',
            options={'verbose_name': 'Urinish javobi', 'verbose_name_plural': 'Urinish javoblari'},
        ),
        migrations.AddField(
            model_name='attempt',
            name='question_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
