# Generated by Django 6.0.2 on 2026-02-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_attempt_options_alter_attemptanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_count',
            field=models.PositiveIntegerField(default=10, help_text='0 bo‘lsa — bankdagi hamma savol beriladi. 10 bo‘lsa — random 10 ta savol tanlanadi.', verbose_name='Nechta savol berilsin'),
        ),
    ]
