# Generated by Django 6.0.2 on 2026-02-11 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_test_questions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions_count',
            field=models.PositiveIntegerField(default=10, help_text='Har attemptda savollar bankidan random tanlanadi (10–50).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)], verbose_name='Nechta savol (10–50)'),
        ),
    ]
