# Generated by Django 6.0.2 on 2026-02-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_test_questions_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Javob varianti', 'verbose_name_plural': 'Javob variantlari'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
