# Generated by Django 6.0.2 on 2026-02-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_choice_options_alter_question_options_and_more'),
        ('users', '0008_alter_department_assigned_tests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar banki'},
        ),
        migrations.CreateModel(
            name='TestRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='exams.test')),
            ],
            options={
                'verbose_name': 'Test qoidasi',
                'verbose_name_plural': 'Test qoidalari',
            },
        ),
    ]
