# Generated by Django 6.0.2 on 2026-02-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_question_options_testrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrule',
            name='attempts_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testrule',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
