# Generated by Django 6.0.2 on 2026-02-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_testrule_attempts_limit_testrule_deadline'),
        ('users', '0010_remove_department_assigned_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrule',
            name='attempts_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='Urinishlar soni'),
        ),
        migrations.AlterField(
            model_name='testrule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='testrule',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muddat'),
        ),
        migrations.AlterField(
            model_name='testrule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='Bo‘lim'),
        ),
        migrations.AlterField(
            model_name='testrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='testrule',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='exams.test', verbose_name='Test'),
        ),
        migrations.DeleteModel(
            name='AssignedTest',
        ),
    ]
