# Generated by Django 6.0.2 on 2026-02-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_testrule_attempts_limit_alter_testrule_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'Multiple choice'), ('true_false', 'True/False'), ('short', 'Short answer'), ('numeric', 'Numeric'), ('essay', 'Essay')], default='multiple', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ball'),
        ),
    ]
