# Generated by Django 6.0.2 on 2026-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_question_question_type_alter_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', "1 ta to'g'ri"), ('multiple', "Bir nechtasi to'g'ri"), ('true_false', "To'g'ri / Noto'g'ri"), ('short', 'Qisqa javob'), ('numeric', 'Numeric'), ('essay', 'Essay')], default='single', max_length=20),
        ),
    ]
