# Generated by Django 6.0.2 on 2026-02-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name="To'g'ri javob (matn/son)"),
        ),
    ]
