# Generated by Django 6.0.2 on 2026-02-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_question_correct_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptanswer',
            options={},
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='numeric_answer',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_choice_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='earned_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', "Bittasi to'g'ri"), ('multiple', "Bir nechtasi to'g'ri"), ('true_false', "To'g'ri / Noto'g'ri"), ('short', 'Qisqa javob'), ('numeric', 'Numeric'), ('essay', 'Essay')], default='single', max_length=20),
        ),
    ]
