# Generated by Django 6.0.2 on 2026-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_alter_attemptanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={},
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('expired', 'Expired'), ('pending_review', 'Pending review')], default='in_progress', max_length=20),
        ),
    ]
