# Generated by Django 6.0.2 on 2026-02-17 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_usertestaccess'),
        ('users', '0010_remove_department_assigned_tests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('branch', 'Branch'), ('department', 'Department'), ('user', 'User')], max_length=20)),
                ('extra_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_policies', to='exams.test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTestAccess',
        ),
        migrations.AddConstraint(
            model_name='attemptpolicy',
            constraint=models.UniqueConstraint(fields=('test', 'scope', 'branch'), name='uniq_test_branch_policy'),
        ),
        migrations.AddConstraint(
            model_name='attemptpolicy',
            constraint=models.UniqueConstraint(fields=('test', 'scope', 'department'), name='uniq_test_department_policy'),
        ),
        migrations.AddConstraint(
            model_name='attemptpolicy',
            constraint=models.UniqueConstraint(fields=('test', 'scope', 'user'), name='uniq_test_user_policy'),
        ),
    ]
