# Generated by Django 6.0.2 on 2026-02-17 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_attemptpolicy_delete_usertestaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrule',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Test davomiyligi (daqiqalarda). Bo'sh bo'lsa Test dagi umumiy vaqt ishlatiladi.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
