# Generated by Django 6.0.2 on 2026-02-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_testrule_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
