# Generated by Django 6.0.2 on 2026-02-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_attempt_duration_minutes_attempt_ends_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='duration_minutes',
        ),
    ]
