# Generated by Django 6.0.2 on 2026-02-18 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_remove_test_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'status'], name='exams_attem_user_id_cf9b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['test', 'status'], name='exams_attem_test_id_1ca1d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user',), name='uniq_in_progress_attempt_per_user'),
        ),
    ]
