# Generated by Django 6.0.2 on 2026-02-19 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_attempt_exams_attem_user_id_cf9b9c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attempt',
            name='uniq_in_progress_attempt_per_user',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='exams_attem_user_id_cf9b9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='exams_attem_test_id_1ca1d8_idx',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('expired', 'Expired'), ('pending_review', 'Pending review')], default='in_progress', max_length=32),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user',), name='uniq_attempt_in_progress_per_user'),
        ),
    ]
